### ISSUE TITLE
parrot integration

### ISSUE THREAD

**Issue by PalinuroSec** [gurayyildirim/dockerized-parrot#1]
hi, can we import this repo on dev.parrotsec.org and maintain it on our official dev platform? we will give you full permissions over the repo

**Comment by gurayops** [comment]
Hi,
Thanks for the communication. I would be very happy for that. I will maintain it at dev.parrotsec.org.
Guray

**Comment by PalinuroSec** [comment]
https://dev.parrotsec.org/parrot/docker-images
repo created, give me your nickname on our platform and i'll give you full access :)

**Comment by gurayops** [comment]
I have registered as gryyldrm 
Thanks! :)

**Comment by PalinuroSec** [comment]
good, i have also registered and uploaded the official docker containers in the docker store with the parrotsec user

do a docker search parrotsec to find them
